nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['^http://localhost:\d+$', 'https://hk.cashloose.com']
        origin_regex: true
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link', 'Content-Disposition']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['^http://localhost:\d+$', 'https://hk.cashloose.com']
            origin_regex: true
